### ISSUE TITLE
[Error] Tools missing in PATH, see missing_tools.txt

### ISSUE THREAD

**Issue by SergioRodLla** [ATpoint/bam2bedgraph#4]
Hi @ATpoint ,

I was trying to run your script with the following parameters:
`./bam2bedgraph.sh --bams "*.bam" --atacseq --mode paired --extend 50 --mode paired --normalize --average --njobs 5`

However, I got the following error:

```
[Info] --atacseq is set, setting --mode to single to use cutsites rather than reads

---------------------------------------------------------------------------------------------
[Version] ::: 1.1

[Info] Running with these parameters:
       --bams          = *.bam
       --mode          = single
       --extend        = 50
       --njobs         = 5
       --atacseq       = TRUE
       --normalize     = TRUE
       --sortthreads   = 1
       --sortmem       = 1G
       --nobigwig      = FALSE
       --average       = TRUE
---------------------------------------------------------------------------------------------

[Error] Tools missing in PATH, see missing_tools.txt
```
I cloned this repo using `git clone`. Am I missing something?

Thank you in advance,
Sergio

**Comment by SergioRodLla** [comment]
Sorry I didn't see the generated file

**Comment by ATpoint** [comment]
Hi, see the generated file `missing_tools.txt`. It contains all software that is not in PATH. It is just these four tools: https://github.com/ATpoint/bam2bedgraph/blob/main/bam2bedgraph.sh#L164

Note please that this repo is for personal use so I will not provide support or take any warranty for whatever you get from it. Hope you understand.
